import '../styles/globals.css'
import Head from 'next/head'
import { TbLetterB } from 'react-icons/tb';



function MyApp({ Component, pageProps }) {
  return(
    <>
     <Head>
        <title>Meu portifolio</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="./asset/icon.png" />
    </Head>
    <Component {...pageProps} />
    </>
   
  )
}

export default MyApp
